# 
# ion-meta configuration file
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'workdir' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
#   Paths should not include trailing "/"
#

workdir: "{PROJECT_FP}"
samplelist_fp: "samples.csv"
paired_end: false

data_path: data
results_path: results
scratch_path: temp
report_path: results/report

# taxonomy database path
taxdb: /results/luze/ion-meta/resources

# deepARG database path
deeparg_dir: /results/luze/ion-meta/resources/deeparg

######################
### CLASSIFICATION ###
######################
# Path to where the classifier (Centrifuge) database will be stored. 
# If possible, this should be on a fast disk. There's at least 1 file in it:
#  1. centrifuge index database
# 
# If below two files are not provided, the workflow will generate them from 
# the above file for the first time:
#  2. sequence data with fasta format (input-sequences.fna.gz)
#  3. mapping file of seqids to taxids (seqid2taxid.map)
centrifuge_dir: /results/luze/ion-meta/resources/classifier_db

# Specify a custom built centrifuge index to use instead of the prebuilt
# Exclude the '.*.cf' suffix
centrifuge_base: bacteria.archaea.viral.fungi.protozoa.human

# Maximum number of assignments per read
# By default this is set to 5 in centrifuge, increase to show more specific assignments
# Set to 1 to implement LCA-classification as in Kraken
centrifuge_max_assignments: 1

# Minimum hit length & score for classifications by centrifuge.
# Because centrifuge doesn't have a filtering algorithm, we use min_length & min_score to filter results.
centrifuge_min_length: 22
centrifuge_min_score: 75

## Host taxid for filtering, e.g., humans: 9606
host_taxid: 9606

# Filtering of genomes
# Here, apply different strategies to filter classification results for viruses, 
# and bacteria (also include fungi,parasites, etc.), respectively.
#
# Note: there is a hidden condition that all identified species shall have >= 3 unique reads
#
# First, for bacteria, ect., do centrifuge filtering and sourmash filtering before further bowtie2 mapping,
# which can help get genome coverage info.


# Centrifuge filtering
# Set minimum read count required during the pre-filtering step to include a genome for downstream analysis
# Note that this is uniquely classified reads
centrifuge_min_read_count: 2000
centrifuge_min_abundance: 0.01


# Sourmash filtering
# Number of reads to define fraction of kmer hashes to compute using sourmash
#
# The number of hashes is 1 in <hash_fraction>
#
# By default this is set to 500000, then we define this fraction to 100, 
# meaning that 1/100 of the input k-mer are used to compute the MinHash signature. 
#
# However, if the number of reads is very large, eg > 500000, the computation is very slow,
# thus we use 1000 as sourmash suggested to speed up
# https://sourmash.readthedocs.io/en/latest/using-sourmash-a-guide.html
#
# Increasing the setting will reduce the disk-space requirements but may also reduce performance.
#
sourmash_fraction_num_reads: 500000

# Minimum coverage estimated from sourmash (0.1 corresponds to 10% of a genome covered by a sample)
sourmash_min_cov: 0.1

###############
### MAPPING ###
###############
bowtie2_threads: 10
bowtie2_params: "--very-sensitive"

# Virus filtering based on bowtie2 mapping results:
#   at least 3 viral reads mapped with minimum mapped quality of 0 (probably 
#   we may need to change this cutoff somehow, but now we use 0 because of we 
#   put all candidate sometimes very similar genomes together for mapping)
#   at least 3 nonoverlapping regions of the most closely matched reference
#
min_mapQ: 0
min_mapped_regions: 3

###############$
### Assembly ###
################
spades: True
assembly_threads: 10
