name: ion-meta

channels:
  - etetoolkit
  - conda-forge
  - biocore
  - bioconda
  - r

dependencies:
  - biopython
  - ete3
  - python=3.6.7
  - snakemake>=4.4.0
  - samtools
  - r=3.6
  - spades
  - megahit
  - matplotlib
  - click
  - ruamel.yaml
  - seqtk
  - pandas
  - bowtie2
  - diamond>=0.9.19
  - centrifuge
  - sourmash
  - bedtools
  - scikit-bio
  - scikit-learn
  - krona
  - blast
  - pandoc
  - r-kableextra
  - r-openxlsx
  - r-rmarkdown
  - r-xfun